---

- name: Ensure zypper packages are installed
  zypper:
    name: python2-docker
    state: latest
    update_cache: yes

- name: Ensure Docker is installed
  yum:
    name:
      - "{{ matrix_docker_package_name }}"
    state: latest
  when: matrix_docker_installation_enabled|bool
