---

- name: Ensure heisenbridge image is pulled
  docker_image:
    name: "{{ matrix_heisenbridge_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_heisenbridge_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}" 
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_heisenbridge_docker_image_force_pull }}" 

- name: Ensure heisenbridge paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - "{{ matrix_heisenbridge_base_path }}"

- name: Ensure heisenbridge registration.yaml installed if provided
  copy:
    content: "{{ matrix_heisenbridge_registration|to_nice_yaml }}"
    dest: "{{ matrix_heisenbridge_base_path }}/registration.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure matrix-heisenbridge.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-heisenbridge.service.j2"
    dest: "{{ matrix_systemd_path }}/matrix-heisenbridge.service"
    mode: 0644
  register: matrix_heisenbridge_systemd_service_result

- name: Ensure systemd reloaded after matrix-heisenbridge.service installation
  service:
    daemon_reload: yes
  when: matrix_heisenbridge_systemd_service_result.changed
