---

- import_tasks: "{{ role_path }}/tasks/ext/rest-auth/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/shared-secret-auth/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/ldap-auth/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/synapse-simple-antispam/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/mjolnir-antispam/setup.yml"
