
- name: Ensure /matrix/awx is empty
  shell: rm -r /matrix/awx/*
  ignore_errors: yes

- name: Ensure /matrix/synapse is empty
  shell: rm -r /matrix/synapse/*
  ignore_errors: yes

- name: Extract from /chroot/export
  shell: tar -xvzf /chroot/export/matrix.tar.gz -C /matrix/

- name: Ensure correct ownership of /matrix/awx
  shell: chown -R matrix:matrix /matrix/awx

- name: Ensure correct ownership of /matrix/synapse
  shell: chown -R matrix:matrix /matrix/synapse

