
- name: Include vars in organisation.yml
  include_vars:
    file: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
  no_log: True

- name: Include vars in hosting_vars.yml
  include_vars:
    file: '/var/lib/awx/projects/hosting/hosting_vars.yml'
  no_log: True

