
- name: Purge all rooms with more then N users
  shell: |
    curl --header "Authorization: Bearer {{ janitors_token.stdout[1:-1] }}" -X POST -H "Content-Type: application/json" -d '{ "delete_local_events": false, "purge_up_to_ts": {{ purge_epoche_time.stdout }}000 }' "{{ synapse_container_ip.stdout }}:8008/_synapse/admin/v1/purge_history/{{ item[1:-1] }}"
  register: purge_command
  
- name: Print output of purge command
  debug: 
    msg: "{{ purge_command.stdout }}"

- name: Pause for 5 seconds to let Synapse breathe
  pause:
    seconds: 5
