
- name: Collect entire room list into stdout
  shell: |
    curl -X GET --header "Authorization: Bearer {{ janitors_token.stdout[1:-1] }}" '{{ synapse_container_ip.stdout }}:8008/_synapse/admin/v1/rooms?from={{ item }}'
  register: rooms_output
  
- name: Print stdout to file
  delegate_to: 127.0.0.1
  shell: |
    echo '{{ rooms_output.stdout }}' >> /tmp/{{ subscription_id }}_room_list_complete.json
