
- name: Purge all rooms with no local users
  shell: |
    curl --header "Authorization: Bearer {{ janitors_token.stdout[1:-1] }}" -X POST -H "Content-Type: application/json" -d '{ "room_id": {{ item }} }' '{{ synapse_container_ip.stdout }}:8008/_synapse/admin/v1/purge_room'
  register: purge_command
  
- name: Print output of purge command
  debug: 
    msg: "{{ purge_command.stdout }}"

- name: Pause for 5 seconds to let Synapse breathe
  pause:
    seconds: 5
