- name: Fail if Etherpad is enabled without the Dimension integrations manager
  fail:
    msg: >-
      To integrate Etherpad notes with Matrix rooms you need to set "matrix_dimension_enabled" to true
  when: "not matrix_dimension_enabled|bool"
